### ISSUE TITLE
NPE Upon joining servers

### ISSUE THREAD

**Issue by zeroeightysix** [zeroeightysix/KAMI#10]
Occasionally, a NullPointerException occurs when trying to join a server or joining singleplayer. The player is then disconnected before joining.

```
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_181]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_181]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1086) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NullPointerException
	at net.minecraft.client.network.NetHandlerPlayClient.func_147282_a(NetHandlerPlayClient.java:298) ~[brz.class:?]
	at net.minecraft.network.play.server.SPacketJoinGame.func_148833_a(SourceFile:76) ~[jh.class:?]
	at net.minecraft.network.play.server.SPacketJoinGame.func_148833_a(SourceFile:13) ~[jh.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:20) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_181]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_181]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 9 more
```

**Comment by zeroeightysix** [comment]
Apparently people are experiencing this outside of KAMI as well. Maybe it's a forge bug?

**Comment by zeroeightysix** [comment]
Confirmed not to be a KAMI issue, closing

**Comment by zeroeightysix** [comment]
Nevermind: https://github.com/ImpactDevelopment/ImpactClient/issues/658#issuecomment-413965692 guess I'll have to go hunting.

**Comment by EmotionalLove** [comment]
It happens on Xdolf too. You have to refresh the server list six billion times before you can join a server.

**Comment by THEREALWWEFAN231** [comment]
99.9% sure its this,  @Inject(method = "handleChunkData",
            at = @At(value = "INVOKE", target = "Lnet/minecraft/world/chunk/Chunk;read(Lnet/minecraft/network/PacketBuffer;IZ)V"),
            locals = LocalCapture.CAPTURE_FAILHARD)
    private void read(SPacketChunkData data, CallbackInfo info, Chunk chunk) {
        KamiMod.EVENT_BUS.post(new ChunkEvent(chunk, data));
    }

i had something very similar, same issue as this, look into it and found if i removed that, it worked, i also found this works,

@Inject(method = "handleChunkData", at = @At("RETURN"), cancellable = true)
	    public void onPlayerUpdate(SPacketChunkData packetIn, CallbackInfo callbackInfo) {
yourstuff();
}
making it at RETURN, at the end of the method, try it(;

**Comment by wine** [comment]
@THEREALWWEFAN231 please use markdown code formatting around the code blocks

**Comment by MrHakan** [comment]
*/

**Comment by dominikaaaa** [comment]
I think this is a 1.12.2 networking specific bug
