### ISSUE TITLE
Please make sutable for mac users

### ISSUE THREAD

**Issue by CombatFlame** [zeroeightysix/KAMI#13]
Greatly appreciated if your client supported mac users, you would get alot more downloads. Mod wouldn't seem to be suitable.

**Comment by zeroeightysix** [comment]
I wasn't aware KAMI didn't work on Mac. Can you post the full crash log? If none exists, please explain in detail what goes wrong.

**Comment by CombatFlame** [comment]
yes theres a crash log

**Comment by zeroeightysix** [comment]
Well.. can you upload it?

**Comment by CombatFlame** [comment]
yes hang on

**Comment by CombatFlame** [comment]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  MixinLoaderForge (KAMI-b9-release (1).jar)
Contact their authors BEFORE contacting forge

// Oops.

Time: 9/18/18 4:13 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from KAMI (kami)
Caused by: java.lang.NoClassDefFoundError: net/minecraftforge/client/event/InputUpdateEvent
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetPublicMethods(Class.java:2902)
	at java.lang.Class.getMethods(Class.java:1615)
	at net.minecraftforge.fml.common.eventhandler.EventBus.register(EventBus.java:81)
	at me.zeroeightsix.kami.KamiMod.init(KamiMod.java:59)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:611)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:253)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:231)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:781)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:348)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: net.minecraftforge.client.event.InputUpdateEvent
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 47 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Mac OS X (x86_64) version 10.13.3
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 598759856 bytes (571 MB) / 973078528 bytes (928 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 7 total; -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.0.2491 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                | Version      | Source                        | Signature                                |
	|:----- |:----------------- |:------------ |:----------------------------- |:---------------------------------------- |
	| UCHI  | minecraft         | 1.12.2       | minecraft.jar                 | None                                     |
	| UCHI  | mcp               | 9.42         | minecraft.jar                 | None                                     |
	| UCHI  | FML               | 8.0.99.99    | forge-1.12.2-14.23.0.2491.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHI  | forge             | 14.23.0.2491 | forge-1.12.2-14.23.0.2491.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHI  | mercurius_updater | 1.0          | MercuriusUpdater-1.12.2.jar   | None                                     |
	| UCHE  | kami              | b9           | KAMI-b9-release (1).jar       | None                                     |

	Loaded coremods (and transformers): 
MixinLoaderForge (KAMI-b9-release (1).jar)

**Comment by CombatFlame** [comment]
<img width="566" alt="screen shot 2018-09-18 at 4 14 52 pm" src="https://user-images.githubusercontent.com/43361139/45719560-1943e500-bb5e-11e8-9fdb-4ed0973849ec.png">

**Comment by CombatFlame** [comment]
Those may help, thanks

**Comment by CombatFlame** [comment]
i am on future 1.12.2

**Comment by CombatFlame** [comment]
it has forge on it

**Comment by CombatFlame** [comment]
<img width="596" alt="screen shot 2018-09-18 at 5 30 54 pm" src="https://user-images.githubusercontent.com/43361139/45722223-9ecc9280-bb68-11e8-8012-5a758b80ddfc.png">

**Comment by CombatFlame** [comment]
this material also didn't work on regular forge on the latest version.
<img width="594" alt="screen shot 2018-09-18 at 5 39 30 pm" src="https://user-images.githubusercontent.com/43361139/45722494-e69fe980-bb69-11e8-9285-30d5f81e03a3.png">

**Comment by CombatFlame** [comment]
Im sure this is a software issue.

**Comment by CombatFlame** [comment]
Please fix

**Comment by zeroeightysix** [comment]
Latest forge is 14.23.4.2759, not 14.23.0.2491 - that's horribly outdated. Update forge.

**Comment by CombatFlame** [comment]
Holy crap I didn't notice that thank you, though now i need to change some gui settings thats all i see of small issues i think you can find that in options.txt
