### ISSUE TITLE
[**BUG**] Crash on beginning

### ISSUE THREAD

**Issue by RajehTXD** [zeroeightysix/KAMI#176]
**Describe the bug**
a crash bug
MC FORGE 1.12.2
**Screenshots**
[Screenshot](https://imgur.com/G1hlBWl)

**Additional context**
If it has to do with a infinite loop then i made my customchat to have random numbers at the end.
suggestion ^

**Comment by RajehTXD** [comment]
Unable to launch
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/Minecraft
	at net.minecraft.client.main.Main.main(SourceFile:38)
	... 6 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.Minecraft
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 7 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:521)
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	... 9 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [mixins.kami.json:MixinMinecraft] from phase [DEFAULT] in config [mixins.kami.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.handleMixinError(MixinTransformer.java:779)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.handleMixinApplyError(MixinTransformer.java:732)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:513)
	... 12 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: Shadow field world was not located in the target class net.minecraft.client.Minecraft. No refMap loaded.
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachFields(MixinPreProcessorStandard.java:563)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:263)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:241)
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1144)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:254)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:353)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.apply(MixinTransformer.java:724)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixins(MixinTransformer.java:703)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:509)
	... 12 more
also

**Comment by RajehTXD** [comment]
OKAY I IDENTIFIED THE ISSUE.
[Here..](https://imgur.com/a/2vgbwiD)

**Comment by RajehTXD** [comment]
the issue is tying to get a loop or atleast have myself a way to do an AntiSpam. I thought of a loop that will keep on changing the Math.Random(); i used. but i kept getting errors. is there anyway to make a rng in my KAMI_SUFFIX (in the CustomChat)

**Comment by S-B99** [comment]
you're gonna have to think of something else to spam the chat because my antispam (that removes spam from the chat) checks for having a random number
