### ISSUE TITLE
OptiFine crash

### ISSUE THREAD

**Issue by zihasz** [zeroeightysix/KAMI#201]
**Describe the bug**
When using KAMI with optifine it crashes instantly at start.

**To Reproduce**
1. Install KAMI
2. Install OptiFine
3 Start Game
4. Crash

**Expected behavior**
I expect minecraft to start properly.

**Screenshots**
N/A

**Additional context**
*Logs*
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NullPointerException
	at me.zeroeightsix.kami.KamiMod.saveConfigurationUnsafe(KamiMod.java:240) ~[KamiMod.class:?]
	at me.zeroeightsix.kami.KamiMod.saveConfiguration(KamiMod.java:232) ~[KamiMod.class:?]
	at net.minecraft.client.Minecraft.save(Minecraft.java:3427) ~[bib.class:?]
	at net.minecraft.client.Minecraft.handler$displayCrashReport$zbe000(Minecraft.java:3415) ~[bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:384) ~[bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) ~[Main.class:?]
	... 6 more
*Mods*
https://gyazo.com/c095589cb7f9dced0862740875d5ccd4
*Other*
Using KAMI Blue but its a kami issue

**Comment by zeroeightysix** [comment]
KAMI forge for 1.12.2 is discontinued. Please make an issue on the kami blue repository if you'd like this fixed.
