### ISSUE TITLE
@zeroeightysix Issue #219 got closed even though nothing was fixed (Posted full log)

### ISSUE THREAD

**Issue by Audition-CSBlock** [zeroeightysix/KAMI#220]
@zeroeightysix 
[crash-client.txt](https://github.com/zeroeightysix/KAMI/files/5163147/crash-client.txt)
Here's my latest crash log

_Originally posted by @Audition-CSBlock in https://github.com/zeroeightysix/KAMI/issues/219#issuecomment-685801050_

**Comment by JerryWester** [comment]
I would recommend bumping your previous issue over creating an entirely separate one

**Comment by zeroeightysix** [comment]
Are you running any other mods alongside KAMI?
Did you build KAMI from source, or did you download the release from GitHub?

**Comment by Audition-CSBlock** [comment]
@zeroeightysix No other mods other than fabric-api, i downloaded the release from github.

**Comment by Audition-CSBlock** [comment]
> 
> 
> I would recommend bumping your previous issue over creating an entirely separate one

I did actually, but it was already closed before i could provide my log, i even posted my log after it was closed but nobody replied.

**Comment by dominikaaaa** [comment]
Try without fabric API

**Comment by littlebroto1** [comment]
I could also suggest deleting your kami config file.

**Comment by Audition-CSBlock** [comment]
Tried both @dominikaaaa and @littlebroto1 suggestions, here's my crash-log:
[crash-client.txt](https://github.com/zeroeightysix/KAMI/files/5177296/crash-client.txt)

**Comment by littlebroto1** [comment]
What is your java version?

**Comment by Audition-CSBlock** [comment]
@littlebroto1 jdk-11.0.8

**Comment by littlebroto1** [comment]
Try starting with the minecraft launcher instead of multimc

**Comment by sourTaste000** [comment]
Launching with jdk version 1.8.0 works, but giving [this](https://paste.ee/p/zTzpD) error when joining servers

**Comment by littlebroto1** [comment]
I think it must be MultiMC. Look at lines 367-370:
```at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

**Comment by dominikaaaa** [comment]
Not, it's not. Just because you launched it with multimc doesn't make multimc the issue. 

This is an issue with imgui not liking jdk 11, and loading classes weirdly on OSX, for the other crash.

**Comment by Audition-CSBlock** [comment]
@dominikaaaa can confirm, just tried on native launcher and it doesn't work.

**Comment by dominikaaaa** [comment]
Launcher has nothing to do with it. 

086 confirmed on Discord it crashes on JDK 11 due to an imgui issue. The JDK 8 crash is normal and caused by crystalaura being unfinished

**Comment by zeroeightysix** [comment]
Confirmed.
If you are experiencing this issue, make sure you run minecraft with Java 8 and not 11.

`help wanted` because frankly, after some googling - I've still no clue what causes this.
Basically, `kotlin-reflect` (or stdlib, who knows) includes files with the `.kotlin_builtins` suffix in the built jar, normally.

These are not present in KAMI as KAMI includes kotlin libraries using fabric's jar-in-jar `include`. If the files are manually extracted from the included jar and put into the KAMI jar, the error still happens - or I'm doing something wrong.

Why it only happens on JDK11 is also a mystery.
