### ISSUE TITLE
AutoTotem crashes on 1.16.3

### ISSUE THREAD

**Issue by jacobwasbeast21** [zeroeightysix/KAMI#239]
I was on 2b2t with KAMI and I had AutoTotem on, I was opening a anvil and I put my rods in the wrong slot, so naturally I pick one of them up but as soon as I did that Minecraft crashes.

I was using my built version of KAMI speaking of 9/15 I did not change anything I just built it how it was.
Java 8

To clarify I was using 1.16.3 with multiconnect.

figured out a couple of things it generally does not function correctly when ever you click in creative or your inventory it is in a werid place every time, also I shift clicked the rods in the click on one which crashed the game.

[22:49:52] [main/FATAL]: Reported exception thrown!
net.minecraft.class_148: Container click
	at net.minecraft.class_1703.method_7593(class_1703.java:187) ~[intermediary-minecraft-1.16.3-client.jar:?]
	at net.minecraft.class_636.method_2906(class_636.java:398) ~[intermediary-minecraft-1.16.3-client.jar:?]
	at me.zeroeightsix.kami.feature.module.AutoTotem.moveTotem(AutoTotem.java:60) ~[KAMI-1.16.3-sep.jar:?]
	at me.zeroeightsix.kami.feature.module.AutoTotem.access$moveTotem(AutoTotem.java:13) ~[KAMI-1.16.3-sep.jar:?]
	at me.zeroeightsix.kami.feature.module.AutoTotem$updateListener$1.invoke(AutoTotem.java:48) ~[KAMI-1.16.3-sep.jar:?]
	at me.zeroeightsix.kami.feature.module.AutoTotem$updateListener$1.invoke(AutoTotem.java:13) ~[KAMI-1.16.3-sep.jar:?]
	at me.zero.alpine.listener.Listener.invoke(Listener.java:97) ~[KAMI-1.16.3-sep.jar:?]
	at me.zero.alpine.bus.EventManager.lambda$post$5(EventManager.java:79) ~[KAMI-1.16.3-sep.jar:?]
	at java.util.concurrent.CopyOnWriteArrayList.forEach(Unknown Source) ~[?:1.8.0_251]
	at me.zero.alpine.bus.EventManager.post(EventManager.java:79) ~[KAMI-1.16.3-sep.jar:?]
	at net.minecraft.class_310.handler$zcg000$tick(class_310.java:3328) ~[intermediary-minecraft-1.16.3-client.jar:?]
	at net.minecraft.class_310.method_1574(class_310.java:1473) ~[intermediary-minecraft-1.16.3-client.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:996) ~[intermediary-minecraft-1.16.3-client.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:656) [intermediary-minecraft-1.16.3-client.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:215) [intermediary-minecraft-1.16.3-client.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_251]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_251]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192) [fabric-loader-0.9.3+build.207.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140) [fabric-loader-0.9.3+build.207.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26) [fabric-loader-0.9.3+build.207.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_251]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_251]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.lang.IndexOutOfBoundsException: Index: 40, Size: 39
	at java.util.ArrayList.rangeCheck(Unknown Source) ~[?:1.8.0_251]
	at java.util.ArrayList.get(Unknown Source) ~[?:1.8.0_251]
	at net.minecraft.class_1703.method_30010(class_1703.java:282) ~[intermediary-minecraft-1.16.3-client.jar:?]
	at net.minecraft.class_1703.method_7593(class_1703.java:177) ~[intermediary-minecraft-1.16.3-client.jar:?]
	... 29 more
[22:49:51] [Netty Client IO #1/ERROR]: Unexpectedly disconnected from server!
io.netty.handler.codec.DecoderException: java.io.IOException: Packet 0/21 (class_2653) was larger than I expected, found 1 bytes extra whilst reading packet 21
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:459) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:647) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:582) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:499) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:461) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
Caused by: java.io.IOException: Packet 0/21 (class_2653) was larger than I expected, found 1 bytes extra whilst reading packet 21
	at net.minecraft.class_2543.decode(class_2543.java:42) ~[intermediary-minecraft-1.16.3-client.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
	... 33 more
[22:49:53] [main/INFO]: [STDOUT]: Shutting down: saving KAMI configuration
[22:49:53] [main/INFO]: [STDOUT]: Configuration saved.
---- Minecraft Crash Report ----
// Don't do that.

Time: 9/15/20 10:49 PM
Description: Container click

java.lang.IndexOutOfBoundsException: Index: 40, Size: 39
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at net.minecraft.class_1703.method_30010(class_1703.java:282)
	at net.minecraft.class_1703.method_7593(class_1703.java:177)
	at net.minecraft.class_636.method_2906(class_636.java:398)
	at me.zeroeightsix.kami.feature.module.AutoTotem.moveTotem(AutoTotem.java:60)
	at me.zeroeightsix.kami.feature.module.AutoTotem.access$moveTotem(AutoTotem.java:13)
	at me.zeroeightsix.kami.feature.module.AutoTotem$updateListener$1.invoke(AutoTotem.java:48)
	at me.zeroeightsix.kami.feature.module.AutoTotem$updateListener$1.invoke(AutoTotem.java:13)
	at me.zero.alpine.listener.Listener.invoke(Listener.java:97)
	at me.zero.alpine.bus.EventManager.lambda$post$5(EventManager.java:79)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(Unknown Source)
	at me.zero.alpine.bus.EventManager.post(EventManager.java:79)
	at net.minecraft.class_310.handler$zcg000$tick(class_310.java:3328)
	at net.minecraft.class_310.method_1574(class_310.java:1473)
	at net.minecraft.class_310.method_1523(class_310.java:996)
	at net.minecraft.class_310.method_1514(class_310.java:656)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at net.minecraft.class_1703.method_30010(class_1703.java:282)

-- Click info --
Details:
	Menu Type: minecraft:anvil
	Menu Class: net.minecraft.class_1706
	Slot Count: 39
	Slot: 40
	Button: 0
	Type: PICKUP
Stacktrace:
	at net.minecraft.class_1703.method_7593(class_1703.java:177)
	at net.minecraft.class_636.method_2906(class_636.java:398)
	at me.zeroeightsix.kami.feature.module.AutoTotem.moveTotem(AutoTotem.java:60)
	at me.zeroeightsix.kami.feature.module.AutoTotem.access$moveTotem(AutoTotem.java:13)
	at me.zeroeightsix.kami.feature.module.AutoTotem$updateListener$1.invoke(AutoTotem.java:48)
	at me.zeroeightsix.kami.feature.module.AutoTotem$updateListener$1.invoke(AutoTotem.java:13)
	at me.zero.alpine.listener.Listener.invoke(Listener.java:97)
	at me.zero.alpine.bus.EventManager.lambda$post$5(EventManager.java:79)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(Unknown Source)
	at me.zero.alpine.bus.EventManager.post(EventManager.java:79)
	at net.minecraft.class_310.handler$zcg000$tick(class_310.java:3328)

-- Affected level --
Details:
	All players: 1 total; [class_746['Jacobwasbeast'/10631, l='ClientLevel', x=130857.74, y=152.00, z=-135621.47]]
	Chunk stats: Client Chunk Cache: 18225, 81
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,64,0), Chunk: (at 0,4,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 164280 game time, 2254115074 day time
	Server brand: Waterfall <- 2b2t
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:449)
	at net.minecraft.class_310.method_1587(class_310.java:2183)
	at net.minecraft.class_310.method_1514(class_310.java:674)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.16.3
	Minecraft Version ID: 1.16.3
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_251, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 94423128 bytes (90 MB) / 855113728 bytes (815 MB) up to 2818572288 bytes (2688 MB)
	CPUs: 4
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx3024m
	Launched Version: MultiMC5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 1060 3GB/PCIe/SSE2 GL version 4.6.0 NVIDIA 451.67, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: fabric/kami, fabric/multiconnect-api, fabric/fabric-resource-loader-v0, fabric/multiconnect, fabric/fabricloader
	Current Language: English (US)
	CPU: 4x Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz
#@!@# Game crashed! Crash report saved to: #@!@# C:\Users\jacob\Desktop\mmc-stable-win32\MultiMC\instances\KAM\.minecraft\crash-reports\crash-2020-09-15_22.49.53-client.txt
AL lib: (EE) alc_cleanup: 1 device not closed
Process exited with code -1.
Clipboard copy at: 15 Sep 2020 22:57:20 -0500

**Comment by zeroeightysix** [comment]
I rewrote AutoTotem, so I have a hard time imagining this bug will happen again. If the rewrite appears not to work, or the crash persists, feel free to reopen!
