### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by SKBotNL** [zeroeightysix/KAMI#281]
**Describe the bug**
When I start minecraft it crashes instantly

**To Reproduce**
1. Start Minecraft

**Expected behavior**
That minecraft just starts normally

**Screenshots**

**Environment**
Did you build KAMI yourself? If so, on what commit? If not, which release did you download?
I used [this one](https://github.com/zeroeightysix/KAMI/actions/runs/309058695)

What operating operating system?
Linux (Ubuntu)

What version of java?
OpenJDK 1.8.0_265 (Java 8 I think)

**Additional context**
[Crash report](https://github.com/zeroeightysix/KAMI/files/5395556/crash-2020-10-17_13.28.19-client.txt)

**Comment by 5HT2** [comment]
Why are you using that branch??

**Comment by SKBotNL** [comment]
Wdym?

**Comment by 5HT2** [comment]
You downloaded a jar from feature/installer, not the fabric branch ![Screenshot_20201017-073825.png](https://user-images.githubusercontent.com/17222512/96336179-c6de9680-104b-11eb-9ad2-f7791c2c14c1.png)

**Comment by SKBotNL** [comment]
Oh I'm stupid, thanks lol

**Comment by SKBotNL** [comment]
So do I need to use this one? https://github.com/zeroeightysix/KAMI/actions/runs/306611130 or am I being really stupid rn

**Comment by 5HT2** [comment]
yes.

**Comment by SKBotNL** [comment]
I will close this issue when it works, if it still crashes I will say it.

**Comment by SKBotNL** [comment]
still a crash

**Comment by SKBotNL** [comment]
`---- Minecraft Crash Report ----
// Oops.

Time: 10/17/20 1:55 PM
Description: Initializing game

org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:364)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:148)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at net.minecraft.class_310.<init>(class_310.java:525)
	at net.minecraft.client.main.Main.main(Main.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:227)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [kami.mixins.json:MixinWorldRenderer] from phase [DEFAULT] in config [kami.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:643)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:595)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:356)
	... 15 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("STORE" ordinal=-1 index=20) on net/minecraft/class_761::modifyBl3 with priority 1000 cannot inject into net/minecraft/class_761::method_3273(Lnet/minecraft/class_4184;Lnet/minecraft/class_4604;ZIZ)V merged by me.jellysquid.mods.sodium.mixin.chunk_rendering.MixinWorldRenderer with priority 1000 [PREINJECT Applicator Phase -> kami.mixins.json:MixinWorldRenderer -> Prepare Injections ->  -> localvar$zjb000$modifyBl3(Z)Z -> Prepare]
	at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:293)
	at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:375)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1255)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1033)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:388)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:570)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
	... 15 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:364)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:148)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at net.minecraft.class_310.<init>(class_310.java:525)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:227)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

-- System Details --
Details:
	Minecraft Version: 1.16.3
	Minecraft Version ID: 1.16.3
	Operating System: Linux (amd64) version 5.4.0-42-generic
	Java Version: 1.8.0_265, Private Build
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Private Build
	Memory: 1679905696 bytes (1602 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 4
	JVM Flags: 8 total; -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-config2: Cloth Config v4 4.7.0-unstable
		fabric: Fabric API 0.24.0+build.411-1.16
		fabric-api-base: Fabric API Base 0.2.0+9f0fb4b895
		fabric-biome-api-v1: Fabric Biome API (v1) 2.0.0+c29459ab95
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea8995
		fabric-command-api-v1: Fabric Command API (v1) 1.0.8+5ce5339895
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+52d3083695
		fabric-containers-v0: Fabric Containers (v0) 0.1.8+045df74f95
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.9+059ea86695
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d95
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.1+f8ac1db295
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+16acbe5b95
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.2+f8ac1db295
		fabric-item-api-v1: Fabric Item API (v1) 1.2.0+f8ac1db295
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.0+438f963695
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.1+730711c695
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+3fa9f7c595
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+74cc3b2095
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.1+432ea18895
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce9995
		fabric-models-v0: Fabric Models (v0) 0.1.1+f8ac1db295
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+b50ffc7b95
		fabric-networking-v0: Fabric Networking (v0) 0.1.10+e00ecb5f95
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.0+c270b09895
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.0+432ea18895
		fabric-particles-v1: fabric-particles-v1 0.2.2+fb0d9b0e95
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.6.0+9f0fb4b895
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.3.1+f8ac1db295
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.1+f8ac1db295
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.2.0+f8ac1db295
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.4+f8ac1db295
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.12+f8ac1db295
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.1+f8ac1db295
		fabric-rendering-v1: Fabric Rendering (v1) 1.3.1+f8ac1db295
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.3.1+facf3bbf95
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+8724984195
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.0+f8ac1db295
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.0.3+ac8e8c5995
		fabric-textures-v0: Fabric Textures (v0) 1.0.4+eae12eb895
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.3+f8ac1db295
		fabricloader: Fabric Loader 0.10.0+build.208
		fiber: fiber 0.24.0-dev
		kami: KAMI 1.16.3-oct
		minecraft: Minecraft 1.16.3
		modmenu: Mod Menu 1.14.6+build.31
		multiconnect: MultiConnect 1.3.29
		multiconnect-api: MultiConnect API 1.3.29
		okzoomer: Ok Zoomer 4.0.1+1.16.2
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.4.0
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.4.0
		satin: Satin 1.5.0
		sodium: Sodium 0.1.0
	Launched Version: fabric-loader-0.10.0+build.208-1.16.3
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GT 710/PCIe/SSE2 GL version 4.6.0 NVIDIA 450.80.02, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: 4x Intel(R) Core(TM) i3-4160 CPU @ 3.60GHz`

**Comment by SKBotNL** [comment]
[crash-2020-10-17_13.55.22-client.txt](https://github.com/zeroeightysix/KAMI/files/5395584/crash-2020-10-17_13.55.22-client.txt)

**Comment by humboldt123** [comment]
What mods do you currently have?

**Comment by SKBotNL** [comment]
I am not on my pc rn but I think I had Sodium, fabric api and okzoomer

**Comment by humboldt123** [comment]
There is an incompatibility with Sodium I believe you have to remove it for now.

**Comment by zeroeightysix** [comment]
I'm fixing it now.

**Comment by SKBotNL** [comment]
Ok Ill try it tomorrow

**Comment by zeroeightysix** [comment]
By the way, I'm fairly sure this is fixed, but don't hesitate to reopen if it still happens!
